plugins {
    id 'java'
}

group = 'de.tresor'
version = '1.4.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.129-stable'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

tasks.processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

tasks.jar {
    archiveFileName = "Tresor-${project.version}.jar"
}
